name = input("Enter your name: ")
college = input("Enter your college: ")
department = input("Enter your department: ")
roll_number = int(input("Enter your roll number: "))

print("\n--------STUDENT ID CARD--------", end="\n\n")
print(f"Name     : {name}")
print(f"College  : {college}")
print(f"Dept     : {department}")
print(f"Roll No. : {roll_number}")
print("\n--------------------------------")
